---
title: "非参统计分析"
format: pptx
editor: visual
---

# 第一章 绪 论

## 相关数理统计知识回顾

### 常见统计的分布及特征

:::: {.columns}

::: {.column width="40%" align=center}
统计分布

-  离散型分布
-  连续型分布
:::

::: {.column width="60%"}
统计特征

-  概率分布函数或密度分布函数
-  期望值与方差
-  协方差与相关系数
:::

::::

---

#### 离散分布

-  二项分布
-  超几何分布
-  均匀分布

---

##### 二项分布: 

-   $X\sim B(n,p)$

-   概率分布函数: $p(X=k)=C^k_np^k(1-p)^{(n-k)}$

-   期望与方差： $\mathrm E(X)=np;\mathrm{Var}(X)=np(1-p)$

---{.fontsize=0.8}

-   证明: $\mathrm E(X)=\sum\limits^{n}_{k=0}kp(x=k)=\sum\limits^{n}_{k=0}k\frac{n!}{k!(n-k)!}p^k(1-p)^{(n-k)}$

$$=np\sum\limits^{n}_{k=1}\frac{(n-1)!}{(k-1)!(n-k)!}p^{(k-1)}(1-p)^{(n-k)}=np $$ $$\mathrm {Var}(X)=\mathrm {E}(X^2)-\mathrm {E}^2(X) $$

$$\mathrm {E}(X^2)=\sum\limits^{n}_{k=0}k^2p(x=k)=\sum\limits^{n}_{k=2}k(k-1)p(x=k)+\mathrm E(X)$$ $$ =p^2\sum\limits^{n}_{k=2}\frac{n(n-1)(n-2)!}{(k-2)!(n-k)!}p^{(k-1)}(1-p)^{(n-k)}+np=n(n-1)p^2+np$$ $$\Rightarrow \mathrm{Var}(X)=np(1-p)$$

-   与正态分布关系:当$n\rightarrow \infty， B(n,p)\overset{L}{\rightarrow}N(np,np(1-p))$

##### 超几何分布: 
-   $X\sim H(n,N,M)$

-   概率分布函数: $p(X=k)=\frac{C^k_NC^{n-k}_{M}}{C^n_{N+M}}$

-   期望与方差： $\mathrm E(X)=n\frac{N}{N+M};\mathrm{Var}(X)=n\frac{NM(N+M-n)}{(N+M)^2(N+M-1)}$

-   与二项分布关系:当$N,M\rightarrow \infty$且$\frac{N}{N+M}\rightarrow p,H(n,N,M)\overset{L}{\rightarrow}B(n,p)$

##### 均匀分布

-   秩统计量分布

-   单变量：$X\sim U^1(n)$

    -   概率分布函数: $p(X=k)=\frac{1}{n}$
    -   期望与方差： $\mathrm E(X)=\frac{n+1}{2};\mathrm{Var}(X)=\frac{n^2-1}{12}$

-   双变量：$(X,Y)\sim U^2(n)$

    -   概率分布函数:$p(X=i,Y=j)=\frac{1}{n(n-1)}$
    -   协方差与相关系数：$\mathrm {Cov}(X,Y)=-\frac{n+1}{12};\rho(X,Y)=-\frac{1}{n-1}$

##### 练习

-   $X\sim B(n=10,p=0.5)$ ，（1）求$P(X=5)$和$p(X=3)$；（2）$P(X\le3)$和p$(X\le8)$ ；（3）如何通过前两问的结果计算$P(3\le X\le 8)$。

-   $X\sim U^1(10)$ ，求$P(X\le 8)$、$P(2\le X\le9)$ 、 $\mathrm E(X)$和$\mathrm{Var}(X)$ 。

-   $(X,Y)\sim U^2(10)$，求$P(X+Y\ge 15)$、$P(4\le X+Y\le 18)$、$\mathrm E(X+Y)$和$\mathrm{Var}(X+Y)$。

-   $X\sim H(n=5,N=10,M=4)$ ，求$P(X=3)$、$P(X\le3)和P(X=5)$。

-   在R语言中求二项分布和超几何分布的概率函数和累计概率函数分布是什么?
